### ISSUE TITLE
Stelpro Maestro zigbee thermostat SMT402AD fingerprint missing

### ISSUE THREAD

**Issue by Kwenchana** [SmartThingsCommunity/SmartThingsEdgeDrivers#1013]
I have 2 other thermostats that works fine and yesterday I tried to add a 3rd one and it kept being added as a Zigbee thing, moved hub closer/factory reset the thermostat to no available, today I tried another identical thermostat in case I got a dud and got the same result.

I then checked the existing thermostats and under driver I only see zigbee thing, looked at the SmartThing zigbee thermostat edge driver fingerprints.yml and it's missing my model.

Works fine with Mariano driver:

  - id: "Stelpro/SMT402AD" # Added M.colmenarejo
    deviceLabel: Stelpro Thermostat
    manufacturer: Stelpro
    model: SMT402AD
    deviceProfileName: thermostat-stelpro-profile

**Comment by lelandblue** [comment]
Hey @Kwenchana Thank you for your reported issue. 

We are only accepting new fingerprints for WWST submissions at this time. I will be closing this issue and still appreciate your efforts.
