### ISSUE TITLE
I can not create new device handler in my account

### ISSUE THREAD

**Issue by weihuan1111** [SmartThingsCommunity/SmartThingsEdgeDrivers#424]
Now, i can not create new device handler in my account?
![image](https://user-images.githubusercontent.com/99949392/206333672-24b26c4e-4c34-4746-b8c0-048507c30f9a.png)

And, before, i could create new device handler in my account
![image](https://user-images.githubusercontent.com/99949392/206333721-2636ae1d-6520-4e31-b1b5-85cdea91749f.png)

So, what happened to make me unable to create new device handler? And is there any way to recover?

@greens

**Comment by greens** [comment]
https://community.smartthings.com/t/the-end-of-groovy-has-arrived/246280
