### ISSUE TITLE
Unknown device is recognized as xiaomi-switch/opple-switch-2

### ISSUE THREAD

**Issue by kisuo** [SmartThingsCommunity/SmartThingsEdgeDrivers#44]
It seems that any unknown device is always matched to `opple-switch-2`, and resulting that it is impossible to use DTH instead.

I scanned a zigbee device which doesn't need external driver. It should use pre-embedded `easyiot Light` DTH driver in ST hub.
-  deviceManufacturerCode: eWeLight
-  deviceModel: ZB-CL01

But when I searched it, it is scanned as name `any` in ST app, and device type is recognized as edge driver of `opple-switch-2`.
I noticed that patterns like `^lumi.switch.l.aeu1` are used by `device:get_model():find(fingerprint.model)` only in `opple` subdriver code, but couldn't understand why it's happening.
To solve this issue, I had to remove every `opple` related code & lines from `fingerprint.yml` and subdriver setup, then I was able to use ST embedded DTH.

I also found another user is also reporting that his Si-Has sensors are also recognized as `any` `opple-switch-2`, and those sensors should use DTH driver instead.

Would you please review this issue?

Thank you.

**Comment by tpmanley** [comment]
@kisuo Can you share fingerprints.yml for the driver which is incorrectly fingerprinting to `opple-switch-2`?

**Comment by kisuo** [comment]
Oops, I think I should have reported it to driver author. Sorry for inconvenience.

**Comment by tpmanley** [comment]
@kisuo No problem, that was what I was originally going to suggest, but I wanted to make sure there wasn't a problem with how fingerprints were being handled.
