### ISSUE TITLE
Please check if "add_hub_to_zigbee_group(...)" works.

### ISSUE THREAD

**Issue by shinasys** [SmartThingsCommunity/SmartThingsEdgeDrivers#50]
I'm making a edge driver, but the "add_hub_to_zigbee_group(...)" doesn't work.
The addHubToGroup(...) work fine in DTH.

**Comment by shinasys** [comment]
@greens Check please.

**Comment by greens** [comment]
@shinasys we're using it in our published drivers, so that would be news to us: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/beta/drivers/SmartThings/zigbee-button/src/zigbee-multi-button/ikea/init.lua#L72

**Comment by shinasys** [comment]
@greens I know too. But this command doesn't work in SmartThings hub.
There was no command to delete the group address, so I performed a SmartThings hub initialization.
And if you test again, the group address is not registered.
But with DTH, you can see that it works.
The ikea button doesn't work either.

**Comment by shinasys** [comment]
@greens Check please.
