### ISSUE TITLE
ST broke the Zigbee Illuminance Sensor Edge driver

### ISSUE THREAD

**Issue by jsconstantelos** [SmartThingsCommunity/SmartThingsEdgeDrivers#543]
Details and images here:

https://community.smartthings.com/t/st-broke-the-zigbee-illuminance-sensor-edge-driver/258299

Today at 4:48pm EST this driver was updated on my hub, and ever since then my hub is flooded with device events and RAW messages from the device. Everything was working great until that happened. Heads up to anyone using the Zigbee Illuminance Sensor edge driver for the Xiaomi Mijia Smart Light Sensor. Mine has been working flawlessly with this edge drive up until now.

Rebooting the hub does nothing, and rejoining the device made it worse. Now it reports nothing at all, not even catchall messages when the button is pressed. It’s broke broke.

I checked my other light sensor, and it’s completely dead and not reporting and I didn’t reset and rejoin that one. It just stopped working the second the updated driver showed up.

**Comment by lelandblue** [comment]
Hello, we will be tracking communication of this reported concern here:

https://community.smartthings.com/t/st-broke-the-zigbee-illuminance-sensor-edge-driver/258299
