### ISSUE TITLE
Xiaomi Illuminance Sensor

### ISSUE THREAD

**Issue by rtorchia** [SmartThingsCommunity/SmartThingsEdgeDrivers#662]
There seems to be no fingerprint for the edge driver for a Zigbee Xiaomi light sensor.
While the old DTH is still active, I have it working with my hub using an open source driver.

Could we add this to the zigbee illuminance edge driver?

Thanks

Some relevant info from the DTH driver:
```
fingerprint profileId: "0104", inClusters: "0000,0400,0003,0001", outClusters: "0003", manufacturer: "LUMI", model: "lumi.sen_ill.mgl01", deviceJoinName: "Xiaomi Mijia Smart Home Light Sensor"

fingerprint profileId: "0104", inClusters: "0000,0400,0003,0001", outClusters: "0003", manufacturer: "XIAOMI", model: "lumi.sen_ill.mgl01", deviceJoinName: "Xiaomi Mijia Smart Home Light Sensor"
```

**Comment by lelandblue** [comment]
Hey @rtorchia - Thank you for your request. We will not be adding fingerprints for devices unless they are persuing WWST Certfication. For more information please reach out to partners@smartthings.com.
